services:
  - type: web
    name: toyota-it-support
    env: php
    buildCommand: |
      composer install
      php artisan key:generate
      touch /tmp/database.sqlite
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    plan: free
